name: resp_client
description: A RESP (REdis Serialization Protocol) client for Dart. It provides a low-level and high-level API to execute Redis commands.
version: 1.1.0
homepage: https://www.github.com/blimster/resp_client

environment:
    sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
    test: ^1.16.0
    pedantic: ^1.10.0
    collection: ^1.15.0
